tfa_sms_auth_form:
    path: /auth
    methods: [GET]
    defaults: { _controller: edgareztfa.sms.controller.auth_form:authAction }

tfa_sms_auth_check:
    path: /check
    methods: [POST]
    defaults: { _controller: edgareztfa.sms.controller.auth_form:checkAction }
