parameters:
    edgareztfa.provider.email.class: EdgarEz\TFABundle\Provider\Email\EmailProvider
    edgareztfa.provider.sms.class: EdgarEz\TFABundle\Provider\SMS\SMSProvider
    edgareztfa.email.controller.auth_form.class: EdgarEz\TFABundle\Provider\Email\Controller\AuthController
    edgareztfa.sms.controller.register.class: EdgarEz\TFABundle\Provider\SMS\Controller\RegisterController
    edgareztfa.sms.controller.auth_form.class: EdgarEz\TFABundle\Provider\SMS\Controller\AuthController
    edgareztfa.listener.class: EdgarEz\TFABundle\EventListener\TFAListener
    edgareztfa.security.auth_handler.class: EdgarEz\TFABundle\Security\AuthHandler

    edgareztfa_tfa_controller.class: EdgarEz\TFABundle\Controller\TFAController

    edgareztfa.security.sms.logouthandler.class: EdgarEz\TFABundle\Provider\SMS\Service\LogoutHandler

services:
    edgareztfa.provider.email:
        class: %edgareztfa.provider.email.class%
        tags:
            - { name: edgareztfa.provider, alias: email }

    edgareztfa.provider.sms:
        class: %edgareztfa.provider.sms.class%
        arguments:
            - @hautelook.router.template
            - @logger
        tags:
            - { name: edgareztfa.provider, alias: sms }

    edgareztfa.security.auth_handler:
        class: %edgareztfa.security.auth_handler.class%
        arguments:
            - @security.token_storage
            - @doctrine

    edgareztfa.listener:
        class: %edgareztfa.listener.class%
        arguments:
            - @security.token_storage
            - @security.access.decision_manager
            - @edgareztfa.security.auth_handler
            - @logger
        tags:
            - { name: kernel.event_subscriber }

    edgareztfa_tfa_controller:
        class: %edgareztfa_tfa_controller.class%
        arguments:
            - @security.token_storage
            - @ezpublish.config.resolver
            - @edgareztfa.security.auth_handler
            - @doctrine
        parent: ezpublish.controller.base

    edgareztfa.email.controller.auth_form:
        class: %edgareztfa.email.controller.auth_form.class%
        arguments:
            - @security.token_storage
            - @ezpublish.config.resolver
            - @mailer
            - @translator
            - $providers;edgar_ez_tfa$
        parent: ezpublish.controller.base

    edgareztfa.sms.controller.register:
        class: %edgareztfa.sms.controller.register.class%
        arguments:
            - @ezpublish.config.resolver
            - @security.token_storage
            - @doctrine
            - @edgareztfa.provider.sms
        parent: ezpublish.controller.base

    edgareztfa.sms.controller.auth_form:
        class: %edgareztfa.sms.controller.auth_form.class%
        arguments:
            - @security.token_storage
            - @ezpublish.config.resolver
            - @translator
            - $providers;edgar_ez_tfa$
            - @doctrine
        parent: ezpublish.controller.base

    edgareztfa.security.sms.logouthandler:
        class: %edgareztfa.security.sms.logouthandler.class%