<?php

namespace EdgarEz\TFABundle\Repository;

use EdgarEz\TFABundle\Entity\TFASMSPhone;

/**
 * TFASMSPhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFASMSPhoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function setPhone($userId, $phone)
    {
        $tfaSMSPhone = new TFASMSPhone();
        $tfaSMSPhone->setUserId($userId);
        $tfaSMSPhone->setPhone($phone);

        $this->getEntityManager()->persist($tfaSMSPhone);
        $this->getEntityManager()->flush();
    }
}
