<?php

namespace EdgarEz\TFABundle\Repository;

/**
 * TFATrustedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TFATrustedRepository extends \Doctrine\ORM\EntityRepository
{
}
